wrk2:
  build: environments/wrk

  links:
   - twcrulesrunner

  hostname: wrk
  domainname: wrk.local

twcrulesrunner:
  build: environments/debug_application

  hostname: app
  domainname: app.local

  ports:
   - "3000:3000"
